version: '3.3'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    volumes:
      # Logging
      - ./nginx/log:/var/log/nginx/
      # Volume đến code ứng dụng, giống bên php-fpm nữa
      - ./:/var/www/html/
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'mingnv'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    # Volumes này đang sử dụng theo dạng biến đó
    # Nó tương đương khai báo VOLUME trong Dockerfile, sinh volume dạng mã băm
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8081:8080
  php-fpm:
    image: php:7.2-fpm
    volumes:
      - ./:/var/www/html/
volumes:
  db_data: {}